# Generated by Django 4.2.11 on 2024-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=200)),
                ("recipe_description", models.TextField(max_length=200)),
                ("recipe_image", models.ImageField(upload_to="recipe_images")),
            ],
        ),
    ]
