# Generated by Django 4.2.11 on 2024-04-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_student_options_alter_studentid_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="date_of_generation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
